services:
  - name: login-service
    source_dir: /functions/tuya
    environment_slug: php
    http_port: 8080
    run_command: php -S 0.0.0.0:8080 login.php
    envs:
      - key: TUYA_API_KEY
        value: "${TUYA_API_KEY}"
        scope: RUN_TIME
      - key: TUYA_API_SECRET
        value: "${TUYA_API_SECRET}"
        scope: RUN_TIME
      - key: TUYA_REGION
        value: "${TUYA_REGION}"
        scope: RUN_TIME
      - key: API_URL
        value: "${API_URL}"
        scope: RUN_TIME

  - name: smart-lock-service
    source_dir: /functions/tuya
    environment_slug: php
    http_port: 8081
    run_command: php -S 0.0.0.0:8081 smart_lock.php
    envs:
      - key: TUYA_API_KEY
        value: "${TUYA_API_KEY}"
        scope: RUN_TIME
      - key: TUYA_API_SECRET
        value: "${TUYA_API_SECRET}"
        scope: RUN_TIME
      - key: TUYA_REGION
        value: "${TUYA_REGION}"
        scope: RUN_TIME