project:
  name: tuya-php-functions
  region: nyc  # Região (ex: nyc, sfo, ams)

packages:
  - name: tuya
    functions:
      - name: login
        runtime: php:8.0  # Usando PHP 8.0
        main: login.php
        web: true
        environment_variables:
          TUYA_API_KEY: "${TUYA_API_KEY}"
          TUYA_API_SECRET: "${TUYA_API_SECRET}"
          TUYA_REGION: "${TUYA_REGION}"
          API_URL: "${API_URL}"
      
      - name: create-temp-password
        runtime: php:8.0
        main: smart_lock.php
        web: true
        environment_variables:
          TUYA_API_KEY: "${TUYA_API_KEY}"
          TUYA_API_SECRET: "${TUYA_API_SECRET}"
          TUYA_REGION: "${TUYA_REGION}"